### ISSUE TITLE
the subtitle on the wordpress.org/plugins page has an error

### ISSUE THREAD

**Issue by ziodave** [insideout10/helixware-plugin#30]
"HelixWare turns WordPress into a video streaming platform. Stop nurturing YouTube with your own contents, publish any video seamlessly on your blog or"

or ... ?

https://wordpress.org/plugins/helixware/

**Comment by cyberandy** [comment]
HelixWare turns WordPress into a Video Hosting platform, supports live broadcasting and makes videos discoverable, searchable, and beautifully organised.

This is 153 char - it should work as introduction - the keyword in this context is `video hosting`.
