### ISSUE TITLE
Adding the HelixWare shortcode in the video assets metadata

### ISSUE THREAD

**Issue by cyberandy** [insideout10/helixware-plugin#39]
Adding the corresponding HelixWare shortcode in the _Attachment Details_ screen will help editors quickly cut and past the shortcode in other areas of the site (i.e. specific fields)  

![image](https://cloud.githubusercontent.com/assets/837037/11303573/e9ffedcc-8fa3-11e5-91e0-c021b3df2422.png)

The field should be _read-only_.

This request came from sichef.

**Comment by ziodave** [comment]
published to wordpress.org, v1.4.0
